### ISSUE TITLE
[Bug] Extensions don't load

### ISSUE THREAD

**Issue by j0hnlux** [Suwayomi/Suwayomi-Server#144]
## Device information
- Tachidesk version: v0.4.2
- Server Operating System: Arch Linux (everything updated)
- Server Desktop Environment: MATE with Compiz
- Server JVM version: { openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode) }

- Client Operating System: same
- Client Web Browser: Firefox updated

## Steps to reproduce
1. Open tachidesk
2. Go to extensions, then loading forever.

### Actual behavior
Extensions loading is stuck.

## Other details
Syer10 said "Tachiyomi removed something that it seems Tachidesk was using"
Also, I did everything correctly.

## Console log
16:46:38.723 [main] INFO  suwayomi.server.ServerSetup - Running Tachidesk v0.4.2 revision r645
16:46:40.027 [main] INFO  suwayomi.server.util.AppMutex - Another instance of Tachidesk is running on 127.0.0.1:4567
16:46:40.027 [main] INFO  suwayomi.server.util.AppMutex - Probably user thought tachidesk is closed so, opening webUI in browser again.

(java:27249): dbind-WARNING **: 16:46:40.275: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-mE958QcrbI: Arquivo ou diretório inexistente
java.io.IOException: Current OS and desktop configuration does not support `browseURL`
	at dorkbox.util.Desktop.browseURL(Desktop.java:154)
	at dorkbox.util.Desktop.browseURL(Desktop.java:115)
	at suwayomi.server.util.Browser.openInBrowser(Browser.kt:32)
	at suwayomi.server.util.AppMutex.handleAppMutex(AppMutex.kt:68)
	at suwayomi.server.ServerSetupKt.applicationSetup(ServerSetup.kt:71)
	at suwayomi.MainKt.main(Main.kt:14)
	at suwayomi.MainKt.main(Main.kt)
16:46:40.303 [main] INFO  suwayomi.server.util.AppMutex - Aborting startup.
16:46:40.304 [main] INFO  suwayomi.server.util.AppExit - Shutting Down Tachidesk. Goodbye!
[kotarou@kotaroupc ~]$ sudo /usr/bin/java -jar /usr/share/java/tachidesk/tachidesk.jar "\$@"
16:46:43.245 [main] INFO  suwayomi.server.ServerSetup - Running Tachidesk v0.4.2 revision r645
16:46:43.832 [main] INFO  suwayomi.server.util.AppMutex - Mutex status is clear, Resuming startup.
16:46:43.834 [main] INFO  xyz.nulldev.androidcompat.bytecode.ModApplier - Applying Javassist mods...
16:46:44.718 [main] INFO  suwayomi.server.database.migration.lib.RunMigrations - Running migrations on database jdbc:h2:/root/.local/share/Tachidesk/database
16:46:45.590 [main] INFO  suwayomi.server.database.migration.lib.RunMigrations - Database version before migrations: 9
16:46:45.593 [main] INFO  suwayomi.server.database.migration.lib.RunMigrations - Migrations finished successfully
16:46:47.591 [main] WARN  dorkbox.jna.linux.GtkTheme - Unable to get tray image size. Using fallback: 24
16:46:47.753 [main] INFO  dorkbox.systemTray.SystemTray - Successfully loaded
16:46:47.864 [main] INFO  io.javalin.Javalin - Static file handler added:
    {urlPathPrefix: "/", path: "/react", location: Location.CLASSPATH}
    Resolved path: 'jar:file:/usr/share/java/tachidesk/tachidesk.jar!/react'
16:46:47.908 [main] INFO  io.javalin.Javalin - 
           __                      __ _
          / /____ _ _   __ ____ _ / /(_)____
     __  / // __ `/| | / // __ `// // // __ \
    / /_/ // /_/ / | |/ // /_/ // // // / / /
    \____/ \__,_/  |___/ \__,_//_//_//_/ /_/

        https://javalin.io/documentation

16:46:47.909 [main] INFO  io.javalin.Javalin - Starting Javalin ...
16:46:48.066 [main] INFO  io.javalin.Javalin - Listening on http://0.0.0.0:4567/
16:46:48.066 [main] INFO  io.javalin.Javalin - Javalin started in 158ms \o/
16:48:04.318 [DefaultDispatcher-worker-3] ERROR suwayomi.server.JavalinSetup - IOException while handling the request
java.io.IOException: ID1ID2: actual 0x00003430 != expected 0x00001f8b
	at okio.GzipSource.checkEqual(GzipSource.kt:197)
	at okio.GzipSource.consumeHeader(GzipSource.kt:110)
	at okio.GzipSource.read(GzipSource.kt:62)
	at okio.RealBufferedSource.select(RealBufferedSource.kt:229)
	at okhttp3.internal.Util.readBomAsCharset(Util.kt:258)
	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
	at suwayomi.tachidesk.impl.extension.github.ExtensionGithubApi.getRepo(ExtensionGithubApi.kt:76)
	at suwayomi.tachidesk.impl.extension.github.ExtensionGithubApi.findExtensions(ExtensionGithubApi.kt:49)
	at suwayomi.tachidesk.impl.extension.ExtensionsList.getExtensionList(ExtensionsList.kt:39)
	at suwayomi.tachidesk.TachideskAPI$defineEndpoints$1$1.invokeSuspend(TachideskAPI.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Syer10** [comment]
Related:
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/488889f17013bd3fc44c9d091e74090a1c7b988d

**Comment by AriaMoradi** [comment]
fixed in 14072bb
